11th-LikeLion-DragOn/DragOn_Front

- src/App.js
- src/pages/SignupPage.js
이후에 충돌 없게끔 App.js 라우팅 형식 맞춰둠. 
VS Code에서 리드미가 형식이 바뀌는지 코드가 동일해도 prettier로 정리가 다르게 돼서 자꾸 충돌이 나서 리드미 지워둔 상태입니다..! 리드미는 VS Code에서 작업하고 코드 복붙해서 둘 다 코드 동일하게 맞춰 놓고 나서 머지하는 게 안전할 듯하네용..
> feat: App.js 라우팅 정리

- src/App.js
- src/components/common/TopBar.js
- src/components/setting/QuitModal.js
- src/pages/ChangeNickPage.js
- src/pages/ChangePasswordPage.js
-회원 탈퇴 모달
-닉네임 수정 페이지
-비밀번호 변경 페이지
> feat: 닉네임 수정, 비밀번호 변경 페이지 UI 

- src/App.js
- src/components/ChallengeListPage/CurrentChallenge.js
- src/components/ChallengeListPage/HistoryChallenge.js
- src/pages/ChallengeListPage.js
-지난 챌린지 컴포넌트
-현재 진행 중인 챌린지 컴포넌트
-챌린지 관리하기 페이지에서 나의 모든 챌린지 리스트 확인 가능
> feat: 챌린지 관리하기 페이지 UI 구현

- src/components/MainPage/Challenge.js
- src/components/MainPage/IconBox.js
- src/pages/FillChallengePage.js
> feat: 챌린지 메꾸기 페이지 추가

- src/components/ChallengeListPage/NoChallenge.js
> feat: 진행 중인 챌린지 없을 때 화면 추가

- src/App.js
- src/components/MainPage/AlarmBox.js
- src/components/MainPage/Calendar.js
- src/components/MainPage/Comment.js
- src/components/MainPage/DayStatus.js
- src/components/MainPage/FillModal.js
- src/components/MainPage/FriendProfile.js
- src/components/MainPage/MainTop.js
- src/components/MainPage/StatusBox.js
- src/pages/FriendMainPage.js
> feat: 친구 home 페이지 구현

- src/App.js
- src/pages/FillChallengePage.js
- src/pages/MainPage.js
챌린지 메꾸기 페이지 달력 추가
vercel 배포 위한 로그인 페이지 path 변경
-
> feat: 챌린지 메꾸기 페이지 달력 추가 및 로그인 페이지 path 변경

- src/pages/MainPage.js
> feat: 챌린지 관리 페이지 이동 함수 추가

- src/components/ChallengeListPage/NoChallenge.js
- src/components/ChallengeListPage/QuitChallenge.js
- src/pages/MakeChallengePage.js
- src/pages/SetPeriodPage.js
- src/pages/SettingPage.js
- src/pages/StartTestPage.js
- src/pages/TestingPage.js
설정페이지, 챌린지 성향테스트, 챌린지관리 및 생성페이지 navigation 추가
> feat: 페이지 navigate 추가

- src/components/MainPage/Challenge.js
- src/components/MainPage/ChallengeModal.js
- src/pages/FillChallengePage.js
- src/pages/MainPage.js
-챌린지 메꾸기 페이지 모달 구현 및 연결
-렌더링 오류 발생해 setTimeout, useEffect 등 사용 -> 현재 setTimeout만 남겨둠
-클릭하는 챌린지에 대한 텍스트값 미반영 상태(ex. 영어 공부, 스페인어 화상수업 등)
> feat: 챌린지 메꾸기 모달 추가 및 오류 수정

- src/api/http.js
- src/api/user.js
- src/components/SignupPage/PasswordInput.js
- src/pages/FriendMainPage.js
- src/pages/SignupPage.js
> feat: 회원가입 아이디, 닉네임 api 연결 및 UI 수정

- src/api/challenge.js
- src/api/user.js
- src/components/ChallengeListPage/HistoryChallenge.js
- src/pages/ChallengeListPage.js
- src/pages/SettingPage.js
> feat: 챌린지 목록 조회 api 수정중

- src/api/challenge.js
- src/api/user.js
- src/components/ChallengeListPage/QuitChallenge.js
- src/pages/ChangeNickPage.js
> feat: 닉네임 변경 api

- src/api/user.js
- src/components/SignupPage/PasswordInput.js
- src/pages/LoginPage.js
- src/pages/SignupPage.js
> feat: 회원가입 api 연결

- src/api/challenge.js
- src/api/user.js
- src/components/ChallengeListPage/NoChallenge.js
- src/components/ChallengeListPage/QuitChallenge.js
- src/components/SettingPage/QuitModal.js
- src/pages/ChallengeListPage.js
- src/pages/ChangePasswordPage.js
- src/pages/MakeChallengePage.js
- src/pages/SettingPage.js
챌린지 그만두기(영구삭제) api 코드 수정
닉네임 변경, 비밀번호 변경 코드 수정
> Feat: 챌린지 삭제 api 연결 

- package-lock.json
- package.json
- src/api/http.js
- src/api/user.js
- src/index.js
- src/pages/LoginPage.js
- src/pages/SettingPage.js
- src/pages/SignupPage.js
- src/recoil/user.js
-설정페이지 css 수정
-recoil 라이브러리 설치
-로그인, 로그아웃 api 연결
npm i 해주세요!!
> feat: 로그인, 로그아웃 api 연결

- src/api/challenge.js
- src/pages/TestingPage.js
Failed to load resource: the server responded with a status of 405 (Method Not Allowed) 에러 뜨는 상태
> feat: 챌린지 성향테스트 결과 전송 api

- src/api/challenge.js
- src/api/user.js
- src/pages/ChangeNickPage.js
- src/pages/ChangePasswordPage.js
- src/pages/SettingPage.js
닉네임 변경 시 중복 확인 
프로필 조회 api 코드 수정 
로컬스토리지에 저장한 토큰 값을 설정페이지에서 받아오지 못하고 있음..
> refactor: 프로필 조회 api 수정 

- package-lock.json
- package.json
- src/api/http.js
- src/api/user.js
- src/index.js
- src/pages/LoginPage.js
- src/pages/SettingPage.js
- src/recoil/user.js
- src/redux/store.js
- src/redux/userSlice.js
-로그인 리덕스 적용
-baseURL 수정
-설정페이지 미사용 코드 일부 삭제
npm i 해주세요!!
> refactor: 로그인 redux 적용

- src/api/user.js
- src/components/SettingPage/QuitModal.js
> feat: 계정 삭제 api 코드 추가

- src/api/friend.js
- src/components/MainPage/FriendProfile.js
- src/components/MainPage/MainTop.js
- src/pages/LoginPage.js
- src/pages/MainPage.js
- src/redux/store.js
-토큰 오류 수정
-store.js 미들웨어 설정 추가
-메인페이지 닉네임 연결
-친구 검색 관련 api 함수 작성
친구 검색 관련 api는 백 코드 수정 후 최종적으로 연결 작업 진행 예정입니다!
> feat: 로그인 토큰 오류 해결 및 친구 검색 관련 api 함수 추가

- src/App.js
- src/api/user.js
- src/components/ChallengeListPage/NoChallenge.js
- src/components/SettingPage/QuitModal.js
- src/pages/ChangePasswordPage.js
- src/pages/MakeChallengePage.js
- src/pages/SettingPage.js
- src/pages/WriteChallengeNamePage.js
챌린지 생성하기 UI 변경 사항 반영 
계정삭제 api 코드 수정
비밀번호 변경 api 코드 수정
> feat: 챌린지 생성하기 UI 변경 사항 반영 및 api 코드 수정

- src/api/challenge.js
- src/components/ChallengeListPage/CurrentChallenge.js
- src/components/ChallengeListPage/DeleteGoalModal.js
- src/components/ChallengeListPage/QuitChallenge.js
- src/pages/TestResultPage.js
- src/pages/WriteChallengeNamePage.js
목표 삭제하기 모달 & 챌린지 그만두기 모달 수정
챌린지 성향테스트 결과 조회 페이지 -> 500
목표 삭제하기 -> 404 뜨는데 현재 생성된 목표id가 없어서 그런 듯 목표 생성하기 기능 완료하고 다시 시도해보기
> feat: 목표 삭제하기 & 챌린지 성향 테스트 결과 조회 api 

- src/api/challenge.js
- src/components/MainPage/MainTop.js
- src/components/MainPage/StatusBox.js
- src/pages/MainPage.js
- src/pages/SearchFriendPage.js
-챌린지 달성 현황 api 연결(css 수정 필요)
challenge.js에서 머지 오류 생기면 깃허브에서 코드 복붙해서 머지해주세요!
> feat: 챌린지 달성 현황 api 연결

- src/api/challenge.js
- src/components/MainPage/Challenge.js
- src/components/MainPage/StatusBox.js
- src/pages/MainPage.js
-refactor: 메인페이지 props 전달 로직 수정
.
> refactor: 메인페이지 props 전달 로직 수정

- src/components/SetPeriodPage/CustomSelect.js
- src/pages/WriteChallengeNamePage.js
> feat: 챌린지 생성하기 api 

- src/api/challenge.js
- src/components/MainPage/FriendProfile.js
- src/components/MainPage/MainTop.js
- src/components/MainPage/StatusBox.js
- src/components/SearchFriendPage/FriendResult.js
- src/pages/MainPage.js
- src/pages/SearchFriendPage.js
> fix: 변수 경로 및 오류 코드 수정

- src/api/challenge.js
- src/components/MainPage/Challenge.js
- src/components/MainPage/MainTop.js
- src/components/MainPage/StatusBox.js
- src/pages/MainPage.js
-챌린지 달성 여부 변경 api 연결 (css props 수정 필요)
.
> feat: 챌린지 달성 여부 변경 api 연결

- src/api/challenge.js
- src/components/MainPage/IconBox.js
- src/components/MainPage/StatusBox.js
- src/pages/MainPage.js
-챌린지 반응 api 연결(css props 수정 필요)
.
> feat: 챌린지 반응 api 연결(css props 수정 필요)

- src/api/challenge.js
- src/components/MainPage/Comment.js
- src/components/MainPage/IconBox.js
- src/components/MainPage/Recomment.js
- src/components/MainPage/RecommentBox.js
- src/components/SearchFriendPage/FriendResult.js
- src/pages/MainPage.js
- src/pages/SearchFriendPage.js
> feat: 댓글 api 연결

- src/api/challenge.js
- src/api/user.js
- src/pages/SettingPage.js
- src/pages/TestResultPage.js
- src/pages/TestingPage.js
base url  수정
챌린지 성향테스트 결과 전송 및 조회 api 수정
> feat: 프로필 조회 api 수정

- src/api/user.js
- src/pages/TestResultPage.js
챌린지 성향테스트 결과 조회 api 연결
결과에 따라 이미지와 텍스트 다르게 렌더링
> feat: 챌린지 성향테스트 결과조회 api & 이미지 렌더링 수정

- src/api/challenge.js
- src/components/MainPage/Challenge.js
- src/components/MainPage/IconBox.js
- src/components/common/TopBar.js
- src/pages/LoginPage.js
- src/pages/MainPage.js
- src/pages/SettingPage.js
- src/redux/userSlice.js
-설정페이지 페이지 경로 수정
-미진행 챌린지 안내 문구 추가
-프로필 조회 api 오류 수정
프로필 내용 조회는 useAppSelector 통해서 사용해주세요!
> feat: 프로필 조회 api 오류 수정

- src/pages/LoginPage.js
- src/pages/MainPage.js
- src/pages/SettingPage.js
- src/redux/userSlice.js
> feat: 설정페이지 프로필 조회 연결

- src/api/friend.js
- src/components/ChallengeListPage/CurrentChallenge.js
- src/components/MainPage/FriendProfile.js
- src/components/MainPage/MainTop.js
- src/pages/ChallengeListPage.js
- src/pages/MainPage.js
-친구 프로필 조회, 친구 달성률 조회 api 함수 작성
.
> feat: 친구 홈 관련 api 함수 작성

- src/components/MainPage/Calendar.js
- src/components/MainPage/FriendProfile.js
- src/pages/FriendMainPage.js
- src/pages/LoginPage.js
- src/pages/MainPage.js
- src/pages/SettingPage.js
-메인페이지 리로딩 시에만 데이터 출력되던 로직 문제 해결
.
> feat: 로그인/로그아웃 리로딩 문제 해결

- src/api/friend.js
- src/components/MainPage/FriendProfile.js
- src/pages/FriendMainPage.js
- src/pages/MainPage.js
-친구 홈 화면 api 연결
-반응, 댓글 조회에서 404 오류 발생
.
> feat: 친구 홈 화면 api 연결(반응, 댓글 오류)

- src/api/challenge.js
- src/components/MainPage/ChallengeModal.js
- src/components/MainPage/FillModal.js
- src/pages/FillChallengePage.js
- src/pages/FriendMainPage.js
-친구 홈 연결 완료
-챌린지 메꾸기 api 함수 작성
.
> feat: 친구 홈 연결 완료 및 챌린지 메꾸기 api 함수 작성

- src/components/MainPage/ChallengeModal.js
- src/components/MainPage/RecommentBox.js
- src/pages/FillChallengePage.js
- src/pages/MainPage.js
> feat: 챌린지 메꾸기 연동 세팅

- src/components/ChallengeListPage/CurrentChallenge.js
- src/components/ChallengeListPage/HistoryChallenge.js
- src/components/ChallengeListPage/QuitChallenge.js
- src/components/MainPage/Calendar.js
- src/components/MainPage/Challenge.js
- src/components/MainPage/IconBox.js
- src/pages/ChallengeListPage.js
-boolean 값 색 변경 구현
-챌린지 그만두기 모달 css 수정
.
> feat: boolean 값 색 변경 구현

- src/components/MainPage/FriendProfile.js
- src/pages/MainPage.js
> feat: 친구 달력 전체 조회 api 연결

- src/api/challenge.js
- src/api/user.js
- src/components/ChallengeListPage/CurrentChallenge.js
- src/components/ChallengeListPage/DeleteGoalModal.js
- src/pages/ChangePasswordPage.js
> feat: 비밀번호 수정 api 연결

- src/components/ChallengeListPage/DeleteGoalModal.js
- src/pages/ChallengeListPage.js
- src/pages/ChangePasswordPage.js
- src/pages/SettingPage.js
> feat: 변경 완료 알림 추가

- src/api/http.js
- src/api/user.js
- src/components/MainPage/Calendar.js
> feat: 날짜 데이터 형식 변경

- src/pages/SettingPage.js
> feat: 설정페이지 코드 복구

- src/components/ChallengeListPage/CurrentChallenge.js
- src/components/MainPage/Calendar.js
- src/pages/ChallengeListPage.js
- src/pages/ChangeNickPage.js
- src/pages/ChangePasswordPage.js
- src/pages/NoChallengeListPage.js
- src/pages/SettingPage.js
-설정 페이지, 챌린지 목록 페이지, 닉네임/비밀번호 변경 페이지 css 수정
.
> style: 페이지 css 변경

- src/components/ChallengeListPage/QuitChallenge.js
- src/components/MainPage/ChallengeModal.js
- src/pages/ChallengeListPage.js
- src/pages/FillChallengePage.js
> style: 챌린지 삭제 모달 css 수정

- src/components/ChallengeListPage/QuitChallenge.js
(버그 해결이 아니라면 이 항목을 삭제하고 풀리퀘해주세요.)
resolve #{이슈번호}
어떤 작업인지 간단하게 작성해주세요.
팀원이 알아야하는 점, 신경써야하는 부분이 있을 경우 작성해주세요.
> fix: 챌린지 그만두기 모달 수정

- src/api/http.js
> feat: https 추가

- src/api/friend.js
> refactor: api 링크 / 추가

- src/api/user.js
- src/components/MainPage/Calendar.js
- src/components/MainPage/ChallengeModal.js
- src/components/MainPage/FillModal.js
- src/components/MainPage/FriendProfile.js
- src/components/MainPage/StatusBox.js
- src/components/common/TopBar.js
- src/pages/FillChallengePage.js
- src/pages/LoginPage.js
- src/pages/MainPage.js
- src/pages/SettingPage.js
- src/redux/userSlice.js
-카카오 로그인 주석 처리
-백 변수 수정사항 반영
-UI 일부 수정
.
> feat: 백 변수 수정사항 반영 및 UI 일부 수정
